# Generated by Django 3.1.3 on 2021-02-26 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_added']},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='date_added',
        ),
    ]
