# Generated by Django 3.1.3 on 2021-03-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicmap', '0003_searchartist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchArtist',
        ),
    ]
