# Generated by Django 3.1.5 on 2021-03-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicmap', '0004_delete_searchartist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
    ]
