# Generated by Django 3.1.5 on 2021-04-03 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicmap', '0006_blogresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogresponse',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicmap.blogresponse'),
        ),
    ]
