# Generated by Django 3.1.5 on 2021-04-04 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicmap', '0007_blogresponse_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicmap.blog'),
        ),
    ]
